"""Added login_activity table

Revision ID: 0bf254857a99
Revises: 0154ab577e47
Create Date: 2023-07-03 12:09:19.654983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf254857a99'
down_revision = '0154ab577e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_activity_login_time'), ['login_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_activity_login_time'))

    op.drop_table('login_activity')
    # ### end Alembic commands ###
