"""Removed slug and unique from product name

Revision ID: 42b38e7f12ce
Revises: e6d90d00e2fc
Create Date: 2023-09-16 15:49:15.976850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b38e7f12ce'
down_revision = 'e6d90d00e2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_product_name_key', type_='unique')
        batch_op.drop_constraint('products_slug_key', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('products_slug_key', ['slug'])
        batch_op.create_unique_constraint('products_product_name_key', ['product_name'])

    # ### end Alembic commands ###
