"""added product model

Revision ID: 435877c3ed93
Revises: da52f60a6c91
Create Date: 2023-07-10 14:49:32.333408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435877c3ed93'
down_revision = 'da52f60a6c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_info', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
