"""added context to product model

Revision ID: 49974524c1f6
Revises: 
Create Date: 2023-08-20 11:52:55.648531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49974524c1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('context')

    # ### end Alembic commands ###
