"""add desgin rationale to product model

Revision ID: 5b8f5fe9c2a7
Revises: 435877c3ed93
Create Date: 2023-07-10 15:31:20.207061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8f5fe9c2a7'
down_revision = '435877c3ed93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_rationale', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('design_rationale')

    # ### end Alembic commands ###
