"""Added ondelete cascade to loginactivity

Revision ID: 5c149ef31b83
Revises: b3bb032ede6e
Create Date: 2023-08-23 15:08:36.296012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c149ef31b83'
down_revision = 'b3bb032ede6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_constraint('login_activity_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('login_activity_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
