"""make design rationale optional or nullable

Revision ID: a73f31e49a6e
Revises: a1c7368ea34e
Create Date: 2023-07-11 10:52:03.448890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73f31e49a6e'
down_revision = 'a1c7368ea34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('design_rationale',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('design_rationale',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
