"""Removed company column

Revision ID: b3bb032ede6e
Revises: 9de62ac5bab5
Create Date: 2023-08-23 15:01:55.240241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bb032ede6e'
down_revision = '9de62ac5bab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
