"""Added new fields to interaction model

Revision ID: cf9ca7b8fa69
Revises: af4a1d5e7fa1
Create Date: 2023-07-20 09:44:31.735545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9ca7b8fa69'
down_revision = 'af4a1d5e7fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_objection', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('product_advice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('product_advice')
        batch_op.drop_column('product_objection')

    # ### end Alembic commands ###
