"""add username column to loginactivity

Revision ID: da52f60a6c91
Revises: 0bf254857a99
Create Date: 2023-07-03 13:09:55.928019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da52f60a6c91'
down_revision = '0bf254857a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))

    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_activity', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
